apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "integration.redhat.com/v1",
          "kind": "ProductOperators",
          "metadata": {
            "name": "integration-product-operators"
          },
          "spec": {
            "install-3scale-operator": true,
            "install-amq-streams-operator": true,
            "install-apicurito-operator": true,
            "install-camel-k-operator": true,
            "install-fuse-online-operator": true,
            "install-service-registry-operator": true,
            "install-sso-operator": true
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: integration-operator.v0.0.12
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ProductOperators is the Schema for the productoperators API
      displayName: Product Operators
      kind: ProductOperators
      name: productoperators.integration.redhat.com
      specDescriptors:
      - displayName: Install 3scale Operator
        path: install-3scale-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install AMQ Streams Operator
        path: install-amq-streams-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install Apicurito Operator
        path: install-apicurito-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install Camel K Operator
        path: install-camel-k-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install Fuse Online Operator
        path: install-fuse-online-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install Service Registry Operator
        path: install-service-registry-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Install Single Sign-On Operator
        path: install-sso-operator
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - displayName: 3scale Operator
        path: status-3scale-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: AMQ Streams Operator
        path: status-amq-streams-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: Apicurito Operator
        path: status-apicurito-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: Camel K Operator
        path: status-camel-k-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: Fuse Online Operator
        path: status-fuse-online-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: Service Registry Operator
        path: status-service-registry-operator
        x-descriptors:
        - urn:alm:descriptor:text
      - displayName: Single Sign-On Operator
        path: status-sso-operator
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1
  description: Installs Red Hat Integration product operators
  displayName: Red Hat Integration
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - integration.redhat.com
          resources:
          - productoperators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - integration.redhat.com
          resources:
          - productoperators/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - operatorgroups
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions/status
          verbs:
          - get
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: integration-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/abkieling/integration-operator:0.0.12
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - integration
  links:
  - name: Integration Operator
    url: https://integration-operator.domain
  maintainers:
  - email: abrianik@redhat.com
    name: Alexandre Kieling
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.12
