apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "integration.redhat.com/v1alpha1",
          "kind": "Installation",
          "metadata": {
            "name": "integration-installation"
          },
          "spec": {
            "3scale-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-3scale",
              "update-channel": "threescale-2.9"
            },
            "amq-streams-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-amq-streams",
              "update-channel": "stable"
            },
            "api-designer-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-apicurito",
              "update-channel": "alpha"
            },
            "camel-k-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-camel-k",
              "update-channel": "techpreview"
            },
            "fuse-online-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-fuse-online",
              "update-channel": "alpha"
            },
            "service-registry-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-service-registry",
              "update-channel": "serviceregistry-1.0"
            },
            "sso-installation-plan": {
              "approval-strategy": "Automatic",
              "enabled": true,
              "namespace": "integration-sso",
              "update-channel": "alpha"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: integration-operator.v0.0.22
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Installation is the Schema for the installations API
      displayName: Installation
      kind: Installation
      name: installations.integration.redhat.com
      specDescriptors:
      - displayName: 3scale Operator
        path: 3scale-installation-plan
      - displayName: Approval Strategy
        path: 3scale-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: 3scale-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: 3scale-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: 3scale-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:threescale-2.6
        - urn:alm:descriptor:com.tectonic.ui:select:threescale-2.7
        - urn:alm:descriptor:com.tectonic.ui:select:threescale-2.8
        - urn:alm:descriptor:com.tectonic.ui:select:threescale-2.9
      - displayName: AMQ Streams Operator
        path: amq-streams-installation-plan
      - displayName: Approval Strategy
        path: amq-streams-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: amq-streams-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: amq-streams-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: amq-streams-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:stable
        - urn:alm:descriptor:com.tectonic.ui:select:amq-streams-1.5.x
        - urn:alm:descriptor:com.tectonic.ui:select:amq-streams-1.x
      - displayName: API Designer Operator
        path: api-designer-installation-plan
      - displayName: Approval Strategy
        path: api-designer-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: api-designer-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: api-designer-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: api-designer-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:alpha
      - displayName: Camel K Operator
        path: camel-k-installation-plan
      - displayName: Approval Strategy
        path: camel-k-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: camel-k-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: camel-k-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: camel-k-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:techpreview
      - displayName: Fuse Online Operator
        path: fuse-online-installation-plan
      - displayName: Approval Strategy
        path: fuse-online-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: fuse-online-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: fuse-online-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: fuse-online-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:alpha
      - displayName: Service Registry Operator
        path: service-registry-installation-plan
      - displayName: Approval Strategy
        path: service-registry-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: service-registry-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: service-registry-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: service-registry-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:serviceregistry-1
        - urn:alm:descriptor:com.tectonic.ui:select:serviceregistry-1.0
      - displayName: Single Sign-On Operator
        path: sso-installation-plan
      - displayName: Approval Strategy
        path: sso-installation-plan.approval-strategy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:Automatic
        - urn:alm:descriptor:com.tectonic.ui:select:Manual
      - displayName: Enabled
        path: sso-installation-plan.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Namespace
        path: sso-installation-plan.namespace
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Update Channel
        path: sso-installation-plan.update-channel
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:alpha
      version: v1alpha1
  description: Installs Red Hat Integration product operators
  displayName: Red Hat Integration
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - integration.redhat.com
          resources:
          - installations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - integration.redhat.com
          resources:
          - installations/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - operatorgroups
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: integration-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/abkieling/integration-operator:0.0.22
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - integration
  links:
  - name: Integration Operator
    url: https://integration-operator.domain
  maintainers:
  - email: abrianik@redhat.com
    name: Alexandre Kieling
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.22
