# permissions for end users to edit productoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: productoperators-editor-role
rules:
- apiGroups:
  - integration.redhat.com
  resources:
  - productoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.redhat.com
  resources:
  - productoperators/status
  verbs:
  - get
